### PR TITLE
fix macos build and install

### PR DESCRIPTION
**Pull request by ra1nb0w**

### CODE REVIEW

**Comment by ra1nb0w** [comment]
if accepted, can you bump version to 0.8.1?
thanks

**Comment by amontefusco** [comment]
Your fixes didn't pass the regression test on Linux: make distcheck fails as follows

```
andrew@andrewp:~/libperseus-sdr$ sudo make distcheck 
make  dist-gzip am__post_remove_distdir='@:'
make[1]: Entering directory '/home/andrew/libperseus-sdr'
if test -d "libperseus_sdr-0.8.0.4-fe92"; then find "libperseus_sdr-0.8.0.4-fe92" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "libperseus_sdr-0.8.0.4-fe92" || { sleep 5 && rm -rf "libperseus_sdr-0.8.0.4-fe92"; }; else :; fi
test -d "libperseus_sdr-0.8.0.4-fe92" || mkdir "libperseus_sdr-0.8.0.4-fe92"
 (cd examples && make  top_distdir=../libperseus_sdr-0.8.0.4-fe92 distdir=../libperseus_sdr-0.8.0.4-fe92/examples \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[2]: Entering directory '/home/andrew/libperseus-sdr/examples'
make  \
  top_distdir="../libperseus_sdr-0.8.0.4-fe92" distdir="../libperseus_sdr-0.8.0.4-fe92/examples" \
  dist-hook
make[3]: Entering directory '/home/andrew/libperseus-sdr/examples'
echo 0.8.0.4-fe92 > ../libperseus_sdr-0.8.0.4-fe92/examples/.tarball-version
make[3]: Leaving directory '/home/andrew/libperseus-sdr/examples'
make[2]: Leaving directory '/home/andrew/libperseus-sdr/examples'
make  \
  top_distdir="libperseus_sdr-0.8.0.4-fe92" distdir="libperseus_sdr-0.8.0.4-fe92" \
  dist-hook
make[2]: Entering directory '/home/andrew/libperseus-sdr'
echo 0.8.0.4-fe92 > libperseus_sdr-0.8.0.4-fe92/.tarball-version
dist_pkgdata_DATA = 
/bin/bash: dist_pkgdata_DATA: command not found
Makefile:1199: recipe for target 'dist-hook' failed
make[2]: *** [dist-hook] Error 127
make[2]: Leaving directory '/home/andrew/libperseus-sdr'
Makefile:863: recipe for target 'distdir' failed
make[1]: *** [distdir] Error 2
make[1]: Leaving directory '/home/andrew/libperseus-sdr'
Makefile:965: recipe for target 'dist' failed
make: *** [dist] Error 2
```
maybe you removed too much in .am file. I'll check tomorrow.

**Comment by ra1nb0w** [comment]
fixed. Unfortunately I can't squash because it fails on previous commits. Tested on ubuntu 18.04.
What do you think to enable this line?
```
hdr_HEADERS = perseus-sdr.h perseusfx2.h perseus-in.h
```
`perseus-in.h` is used by sdrangel

thanks

**Comment by amontefusco** [comment]
> fixed. Unfortunately I can't squash because it fails on previous commits. Tested on ubuntu 18.04.

Ok, thanks.

> What do you think to enable this line?
> 
> ```
> hdr_HEADERS = perseus-sdr.h perseusfx2.h perseus-in.h
> ```
> 
> `perseus-in.h` is used by sdrangel

That sounds strange as that are internal structures that shouldn't be exposed outside.
For what purpose are they using that ?

**Comment by ra1nb0w** [comment]
the same thing I said ;-)
he checks `descr->firmware_downloaded` see [deviceperseusscan.cpp](https://github.com/f4exb/sdrangel/blob/master/devices/perseus/deviceperseusscan.cpp)

**Comment by amontefusco** [comment]
> fixed. Unfortunately, I can't squash because it fails on previous commits. Tested on Ubuntu 18.04.

Ok, thanks.

> What do you think to enable this line?
> 
> ```
> hdr_HEADERS = perseus-sdr.h perseusfx2.h perseus-in.h
> ```
> 
> `perseus-in.h` is used by sdrangel

That sounds strange as that are internal structures that shouldn't be exposed outside.
For what purpose are they using that?

**Comment by ra1nb0w** [comment]
it is the same as before; do you lost something?

**Comment by amontefusco** [comment]
> the same thing I said ;-)
> he checks `descr->firmware_downloaded` see [deviceperseusscan.cpp](https://github.com/f4exb/sdrangel/blob/master/devices/perseus/deviceperseusscan.cpp)

he should just assume it is not downloaded and call anyway perseus_firmware_download (that, after all, is what he is doing two lines below).

**Comment by ra1nb0w** [comment]
same patch that I sent ;-)
https://github.com/f4exb/sdrangel/pull/327/files#diff-81d79064fa676b4bbb41365b1aaacdaf
so I report your statement and you can merge this. can you bump up version, like 0.8.1? thanks

**Comment by amontefusco** [comment]
@amontefusco
Merge pull request #9: fix macos build and install (many thanks to ra1nb0w)

**Comment by ra1nb0w** [comment]
thank you and have a nice holiday!

**Pull request merged**
